channels:
  - jmcmurray
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.8
  - pip
  - os
  - pip:
      - numpy
      - jupyter
      - argparse
      - urllib3
      - beautifulsoup4
      - pylint
